name: Release

on:
  push:
    branches:
      - main
  release:
    types:
      - published
      - unpublished
      - created
      - edited
      - deleted
      - prereleased
      - released

env:
  NODE_VERSION: '10.x'

defaults:
  run:
    shell: bash

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - id: setup-node
      name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - id: sanity-check
      name: Sanity check
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        STEPS_CONTEXT: ${{ toJson(steps) }}
        RUNNER_CONTEXT: ${{ toJson(runner) }}
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: |
        printenv
        echo "$PATH"
        echo "$GITHUB_CONTEXT"
        echo "$JOB_CONTEXT"
        echo "$STEPS_CONTEXT"
        echo "$RUNNER_CONTEXT"
        echo "$STRATEGY_CONTEXT"
        echo "$MATRIX_CONTEXT"
        which node
        node --version
        which npm
        npm --version
        which grunt
        grunt --version
        which make
        make --version
        which jq
        jq --version
        pwd
        ls -lah .

    - id: cache-dependencies
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          **/.cache
        key: node-modules-${{ hashFiles('package.json') }}

    - id: install-dependencies
      name: Install dependencies
      if: |
        (steps.cache-dependencies.outputs.cache-hit != 'true')
      run: |
        npm install

  tag:
    name: Tag
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push'
    needs: [ setup ]
    steps:
    - id: setup-node
      name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - id: cache-dependencies
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          **/.cache
        key: node-modules-${{ hashFiles('package.json') }}

    - id: identity
      name: Identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git config --list

    - id: tag-commit
      name: Tag commit
      run: |
        git fetch --all --verbose
        git tag --list
        git show-ref --tags -d
        git ls-remote --tags origin
        
        #npx semver --increment patch $(/usr/bin/git tag --sort=committerdate --list | tail -n1)
        
        #VERSION=v$(npx semver --increment patch $(git tag --sort=committerdate --list | tail -n1))
        #git tag -a $VERSION -m "$VERSION"
        #git push origin $VERSION

  release:
    name: Release
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release'
    needs: [ setup ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-published:
    name: Release > published
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release' && github.event.action == 'published'
    needs: [ release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-unpublished:
    name: Release > unpublished
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release' && github.event.action == 'unpublished'
    needs: [ release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-created:
    name: Release > created
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release' && github.event.action == 'created'
    needs: [ release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-edited:
    name: Release > edited
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release' && github.event.action == 'edited'
    needs: [ release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-deleted:
    name: Release > deleted
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release' && github.event.action == 'deleted'
    needs: [ release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-prereleased:
    name: Release > prereleased
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release' && github.event.action == 'prereleased'
    needs: [ release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-released:
    name: Release > released
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release' && github.event.action == 'released'
    needs: [ release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
