name: Release

on:
  push:
    branches:
      - main
  release:
    types:
      - published
      - unpublished
      - created
      - edited
      - deleted
      - prereleased
      - released

env:
  NODE_VERSION: '10.x'

defaults:
  run:
    shell: bash

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - id: setup-node
      name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - id: sanity-check
      name: Sanity check
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        STEPS_CONTEXT: ${{ toJson(steps) }}
        RUNNER_CONTEXT: ${{ toJson(runner) }}
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: |
        printenv
        echo "$PATH"
        echo "$GITHUB_CONTEXT"
        echo "$JOB_CONTEXT"
        echo "$STEPS_CONTEXT"
        echo "$RUNNER_CONTEXT"
        echo "$STRATEGY_CONTEXT"
        echo "$MATRIX_CONTEXT"
        which node
        node --version
        which npm
        npm --version
        which grunt
        grunt --version
        which make
        make --version
        which jq
        jq --version
        pwd
        ls -lah .

    - id: cache-dependencies
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          **/.cache
        key: node-modules-${{ hashFiles('package.json') }}

    - id: install-dependencies
      name: Install dependencies
      if: |
        (steps.cache-dependencies.outputs.cache-hit != 'true')
      run: |
        npm install

  tag:
    name: Tag
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push'
    needs: [ setup ]
    steps:
    - id: setup-node
      name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - id: cache-dependencies
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          **/.cache
        key: node-modules-${{ hashFiles('package.json') }}

    - id: identity
      name: Identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git config --list

    - id: tag-commit
      name: Tag commit
      run: |
        git fetch --all --verbose
        
        # echoes, https://www.youtube.com/watch?v=53N99Nim6WE
        echo "0"
        echo $(git ls-remote --tags --sort=version:refname origin)
        echo "1"
        echo $(git ls-remote --tags --sort=version:refname origin | awk '!/\^\{\}$/')
        echo "2"
        echo $(git ls-remote --tags --sort=version:refname origin | awk '!/\^\{\}$/' | tail -n1)
        echo "3"
        echo $(git ls-remote --tags --sort=version:refname origin | awk '!/\^\{\}$/' | tail -n1 | sed 's/.*refs\/tags\///g')
        echo "4"
        
        # list remote tags, ignore dereferenced tags, get the last one, leave only the version part
        LAST_VERSION=$(git ls-remote --tags --sort=version:refname origin | awk '!/\^\{\}$/' | tail -n1 | sed 's/.*refs\/tags\///g')
        
        # bump version to next patch, prepend with build number
        NEW_VERSION=v$(npx semver --increment patch $LAST_VERSION).${{ github.run_number }}
        echo $NEW_VERSION
        
        # push new tag
        git tag -a $NEW_VERSION -m "$NEW_VERSION"
        git push origin $NEW_VERSION

  release:
    name: Release
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release'
    needs: [ setup ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-published:
    name: Release > published
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'published'
    needs: [ tag, release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-unpublished:
    name: Release > unpublished
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'unpublished'
    needs: [ tag, release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-created:
    name: Release > created
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'created'
    needs: [ tag, release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-edited:
    name: Release > edited
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'edited'
    needs: [ tag, release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-deleted:
    name: Release > deleted
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'deleted'
    needs: [ tag, release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-prereleased:
    name: Release > prereleased
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'prereleased'
    needs: [ tag, release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release-released:
    name: Release > released
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'released'
    needs: [ tag, release ]
    steps:
    - id: print-context
      name: Print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
